### ISSUE TITLE
Error: The edge native module is not available at /../node_modules/electron-edge-js/build/Release/edge_coreclr.node. 

### ISSUE THREAD

**Issue by pmahend1** [agracio/edge-js#116]
I have added the package to my VS Code extension. It works fine on Windows , but on Mac I get this exception.

Mac does have mono, dotnet sdk(core) installed. 

Isnt this prebuilt for the NodeJs version that VS Code currently uses?
 ```
Electron: 7.3.2
Node.js: 12.8.1
```

```log
Error: The edge native module is not available at /Users/FirstName.LastName/Projects/GitHub/Project_Dir/node_modules/electron-edge-js/build/Release/edge_coreclr.node. You can use EDGE_NATIVE environment variable to provide alternate location of edge.node. If you need to build edge.node, follow build instructions for your platform at https://github.com/tjanczuk/edge
	at Object.<anonymous> (/Users/FirstName.LastName/Projects/GitHub/Project_Dir/node_modules/electron-edge-js/lib/edge.js:46:11)
	at Module._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:360)
	at Object..js (internal/modules/cjs/loader.js:939:10)
	at Module.load (internal/modules/cjs/loader.js:782:32)
	at internal/modules/cjs/loader.js:695:12
	at electron/js2c/asar.js:717:26
	at Function.<anonymous> (electron/js2c/asar.js:717:26)
	at Function.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1005:775)
	at Function.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:661)
	at Function._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:971:844)
	at Module.require (internal/modules/cjs/loader.js:822:19)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:135)
	at /Users/FirstName.LastName/Projects/GitHub/Project_Dir/out/extension.js:61:32
	at Generator.next (<anonymous>)
	at /Users/FirstName.LastName/Projects/GitHub/Project_Dir/out/extension.js:8:71
	at new Promise (<anonymous>)
	at /Users/FirstName.LastName/Projects/GitHub/Project_Dir/out/extension.js:4:12
	at format (/Users/FirstName.LastName/Projects/GitHub/Project_Dir/out/extension.js:43:12)
	at /Users/FirstName.LastName/Projects/GitHub/Project_Dir/out/extension.js:26:27
	at Generator.next (<anonymous>)
	at /Users/FirstName.LastName/Projects/GitHub/Project_Dir/out/extension.js:8:71
	at new Promise (<anonymous>)
	at /Users/FirstName.LastName/Projects/GitHub/Project_Dir/out/extension.js:4:12
	at /Users/FirstName.LastName/Projects/GitHub/Project_Dir/out/extension.js:23:30
	at Object._withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:590:672)
	at Object.withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:590:426)
	at Object.withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:944:395)
	at /Users/FirstName.LastName/Projects/GitHub/Project_Dir/out/extension.js:19:33
	at Generator.next (<anonymous>)
	at /Users/FirstName.LastName/Projects/GitHub/Project_Dir/out/extension.js:8:71
	at new Promise (<anonymous>)
	at /Users/FirstName.LastName/Projects/GitHub/Project_Dir/out/extension.js:4:12
	at /Users/FirstName.LastName/Projects/GitHub/Project_Dir/out/extension.js:17:107
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:937:271
	at Object.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:598:242)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:937:260
	at _executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:642:374)
	at _.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:642:749)
	at m._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:819:926)
	at m._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:819:618)
	at m._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:818:252)
	at m._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:817:6)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:815:161
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:239:494)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1007:179
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:239:494)
	at Object._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:244:17)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:241:67
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:236:949)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:236:301
	at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:245:572)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by pmahend1** [comment]
Wrong repository. Raised issue in [electron-edge-js#94](https://github.com/agracio/electron-edge-js/issues/94)
