### ISSUE TITLE
Unable to resolve reference to System.

### ISSUE THREAD

**Issue by cosminonea** [agracio/edge-js#198]
I am trying to run samples/203_x509store.js on an M3 Mac but I get the following error: `Error: Unable to resolve reference to System.`

I get a similar error with any other dll I try to reference.

Are the samples supposed to run on all platforms?

```
/oss/edge-js/lib/edge.js:178
    return edge.initializeClrFunc(options);
                ^
Error: Unable to resolve reference to System.
    at exports.func (/oss/edge-js/lib/edge.js:178:17)
    at Object.<anonymous> (/oss/edge-js/samples/203_x509store.js:5:29)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  TargetSite: {
    Name: '',
    DeclaringType: '',
    ReflectedType: '',
    MemberType: '',
    MetadataToken: '',
    Module: '',
    IsSecurityCritical: '',
    IsSecuritySafeCritical: '',
    IsSecurityTransparent: '',
    MethodHandle: '',
    Attributes: '',
    CallingConvention: '',
    ReturnType: '',
    ReturnTypeCustomAttributes: '',
    ReturnParameter: '',
    IsCollectible: '',
    IsGenericMethod: '',
    IsGenericMethodDefinition: '',
    ContainsGenericParameters: '',
    MethodImplementationFlags: '',
    IsAbstract: '',
    IsConstructor: '',
    IsFinal: '',
    IsHideBySig: '',
    IsSpecialName: '',
    IsStatic: '',
    IsVirtual: '',
    IsAssembly: '',
    IsFamily: '',
    IsFamilyAndAssembly: '',
    IsFamilyOrAssembly: '',
    IsPrivate: '',
    IsPublic: '',
    IsConstructedGenericMethod: '',
    CustomAttributes: ''
  },
  Message: 'Unable to resolve reference to System.',
  Data: {},
  InnerException: null,
  HelpLink: null,
  Source: 'edge-cs-coreclr',
  HResult: -2146233088,
  StackTrace: '   at EdgeCompiler.TryCompile(String source, List`1 references, IDictionary`2 compileAssemblies, String& errors, Assembly& assembly)\n' +
    '   at EdgeCompiler.CompileFunc(IDictionary`2 parameters, IDictionary`2 compileAssemblies)\n' +
    '   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)\n' +
    '   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)',
  Name: 'System.Exception',
  name: 'System.Exception'
}

Node.js v20.10.0

Process finished with exit code 1
```

**Comment by agracio** [comment]
Added `listCertificates` method to https://github.com/agracio/edge-js-quick-start.
