### ISSUE TITLE
Edge-js: Uncaught Error: The specified procedure could not be found. \\? ... \edge_nativeclr.node

### ISSUE THREAD

**Issue by JDP124** [agracio/edge-js#208]
Hi I wondered if you could take a look at the below, it seems I can't get Edge-js to run in my project.

I’m trying to use edge-js to run a .NET dll in a Typescript [vscode LSP extension ](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) I’m working on. I have a local seperate Typescript project that successfully runs the dll using Edge-js. But can’t seem to get Edge-js to run because of this error:

adding a reference to edge.func() 
`const method = edge.func(filename);`
`edge.func("");`

raises this error:
Uncaught Error Error: The specified procedure could not be found.
\\?\c:\{path to project}\node_modules\edge-js\lib\native\win32\x64\18.19.1\edge_nativeclr.node
    at func (electron/js2c/node_init:2:2214)
    at Module._extensions..node (internal/modules/cjs/loader:1356:18)
    at func (electron/js2c/node_init:2:2214)
    at Module.load (internal/modules/cjs/loader:1126:32)
    at Module._load (internal/modules/cjs/loader:967:12)
    at c._load (electron/js2c/node_init:2:13672)
    at Module.require (internal/modules/cjs/loader:1150:19)
    at require (internal/modules/cjs/helpers:119:18)
    at <anonymous> (c:\VisualfilesSrc\V6.X\VSCScriptEditor\node_modules\edge-js\lib\edge.js:53:8)
    at Module._compile (internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (internal/modules/cjs/loader:1326:10)
    at Module.load (internal/modules/cjs/loader:1126:32)
    at Module._load (internal/modules/cjs/loader:967:12)
    at c._load (electron/js2c/node_init:2:13672)
    at Module.require (internal/modules/cjs/loader:1150:19)
    at require (internal/modules/cjs/helpers:119:18)
    at <anonymous> (c:\VisualfilesSrc\V6.X\VSCScriptEditor\server\src\server.ts:47:1)
    at Module._compile (internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (internal/modules/cjs/loader:1326:10)
    at Module.load (internal/modules/cjs/loader:1126:32)
    at Module._load (internal/modules/cjs/loader:967:12)
    at c._load (electron/js2c/node_init:2:13672)
    at executeUserEntryPoint (internal/modules/run_main:101:12)
    at <anonymous> (internal/main/run_main_module:23:47)

The node module is indeed where it should be.

Node version : v20.11.0 I have tried Edge-js v21.7.2 and v22.1.1

The closest thing I could find online is this: [Error: The specified module could not be found](https://stackoverflow.com/questions/41253450/error-the-specified-module-could-not-be-found) but this error is module not found, mine is procedure not found, not sure if relevant.

Looking into Edge.js file it seems the project is using Node v18.18.2, not sure if this is relevant, but my Typescript project that does run Edge-js without issue shows its running v20.11.0

`determineVersion() =  18.19.1
process.versions.node =  18.18.2`

Thanks in advance for any assistance

**Comment by JDP124** [comment]
Amazing, electron-edge-js runs. thank you.
