### ISSUE TITLE
Cannot call .NET Core 2.0 dll

### ISSUE THREAD

**Issue by Pat-Ayres** [agracio/edge-js#22]
When I try to call a .NET core 2.0 dll after setting the environment variable `EDGE_USE_CORECLR=1` I get the following error:
```
PS C:\code\node-edge-test> node .\sample.js

C:\code\node-edge-test\node_modules\edge-js\lib\edge.js:178
    return edge.initializeClrFunc(options);
                ^
Error: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.    at Object.exports.func (C:\code\node-edge-test\node_modules\edge-js\lib\edge.js:178:17)
    at Object.<anonymous> (C:\code\node-edge-test\sample.js:32:36)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

The exact same code works with a .NET Framework 4.6.1 dll

js: 
```
const path = require('path');
const edge = require('edge-js');
const baseNetAppPath = path.join(__dirname, '\\QuickStartFramework\\QuickStartFramework.Core\\bin\\Debug');
const coreNetAppPath = path.join(__dirname, '\\QuickStart\\QuickStart.Core\\bin\\Debug\\netcoreapp2.0');

process.env.EDGE_USE_CORECLR = 1;
// process.env.EDGE_APP_ROOT = baseNetAppPath;
process.env.EDGE_APP_ROOT = coreNetAppPath;

// const getFrameworkAppDomainDirectory = edge.func({
// 	assemblyFile: path.join(baseNetAppPath, 'QuickStartFramework.Core.dll'),
// 	typeName: 'QuickStartFramework.Core.LocalMethods',
// 	methodName: 'GetAppDomainDirectory'
// });

// getFrameworkAppDomainDirectory('', (e,r) => {
// 	if (e) throw error;
// 	console.log(r);
// });

const getAppDomainDirectory = edge.func({
	assemblyFile: path.join(coreNetAppPath, 'QuickStart.Core.dll'),
	typeName: 'QuickStart.Core.LocalMethods',
	methodName: 'GetAppDomainDirectory'
});

getAppDomainDirectory('', (e,r) => {
	if (e) throw error;
	console.log(r);
});
```

csharp:
```
using System;
using System.Threading.Tasks;

namespace QuickStart.Core
{
    public class LocalMethods
    {
        public async Task<object> GetAppDomainDirectory(dynamic input) => AppDomain.CurrentDomain.BaseDirectory;
        public async Task<object> GetLocalDateTime(dynamic input) => DateTime.Now.ToString("yyyy:MM:dd HH:mm:ss");
    }
}
```

Is there something else I am missing?

**Comment by agracio** [comment]
I have created "_quick start_" app for .NET Core here: https://github.com/agracio/edge-js-quick-start.
Works fine when building dlls using .NET Core 2.0.

**Comment by sandipbiswasbehala** [comment]
.net standard project is not running.. Have you checked it. .net core project is ok. And thanks for .net core project. But please show us some way to work with .net core 3.0 or .net standard 2.0  + EntityFramwork Core 3.0.
