### ISSUE TITLE
App pool crashes when calling NodeJS from CLR

### ISSUE THREAD

**Issue by Inc33** [agracio/edge-js#34]
I'm getting this error in the simple sample:
Attempted to read or write protected memory. This is often an indication that other memory is corrupt
   at EdgeJs.Edge.NodeStartx64(Int32 argc, String[] argv)
   at EdgeJs.Edge.<>c__DisplayClass14_0.<Func>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

What's interesting though, is if I restart the app pool, it starts working. But if i change something, and do a build again, without stopping the app pool in the meantime, it will crash again, and to make it work again, I need to restart the app pool.

Le me know, if you know about this issue, and how can I help to find the issue.

**Comment by agracio** [comment]
Issue fixed in https://github.com/agracio/edge-js/pull/119, please update to newest nuget package.
