### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by choukui** [agracio/edge-js#44]
node v-10.6.0; 报一下错误，这是怎么回事？

internal/modules/cjs/loader.js:760 Uncaught Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:760:18)
    at Module.load (internal/modules/cjs/loader.js:623:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:562:12)
    at Function.Module._load (internal/modules/cjs/loader.js:554:3)
    at Module.require (internal/modules/cjs/loader.js:661:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (G:\work\zhilan\nwjs-sdk-v0.31.5-win-x64\node_modules\edge-js\lib\edge.js:54:8)
    at Module._compile (internal/modules/cjs/loader.js:713:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:730:10)
    at Module.load (internal/modules/cjs/loader.js:623:32)

**Comment by agracio** [comment]
From your comment on another issue I am assuming this is related to `nwjs`? `nwjs` is not supported.

**Comment by rbeesley** [comment]
I had the same result as @ghogen, trying to use Quokka.js in VS Code against npm 10.12.0. However, since I was able to get the helloWorld example to execute, I don't think it is a problem with edge-js unless it does something vastly different than other libraries.
