### ISSUE TITLE
Feature request: Support for Node.js 12.x

### ISSUE THREAD

**Issue by informaticienzero** [agracio/edge-js#72]
Would be very nice to use this amazing project with Node v12.x. :)

**Comment by informaticienzero** [comment]
Actually, trying to compile with Node v12.x results in errors.

```
root@dc71ba70a640:/tmp/simple-samples/edge-js# node-gyp build --target=$(node --version)
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@12.0.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/tmp/simple-samples/edge-js/build'
  CXX(target) Release/obj.target/edge_coreclr/src/common/v8synchronizationcontext.o
  CXX(target) Release/obj.target/edge_coreclr/src/common/callbackhelper.o
  CXX(target) Release/obj.target/edge_coreclr/src/common/edge.o
../src/common/edge.cpp: In function 'void init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)':
../src/common/edge.cpp:65:72: error: no matching function for call to 'v8::FunctionTemplate::GetFunction()'
         Nan::New<v8::FunctionTemplate>(initializeClrFunc)->GetFunction());
                                                                        ^
In file included from ../src/common/edge_common.h:4:0,
                 from ../src/common/edge.cpp:5:
/root/.node-gyp/12.0.0/include/node/v8.h:5947:46: note: candidate: v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/root/.node-gyp/12.0.0/include/node/v8.h:5947:46: note:   candidate expects 1 argument, 0 provided
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-unused-private-field'
cc1plus: warning: unrecognized command line option '-Wno-redundant-move'
cc1plus: warning: unrecognized command line option '-Wno-mismatched-tags'
edge_coreclr.target.mk:133: recipe for target 'Release/obj.target/edge_coreclr/src/common/edge.o' failed
make: *** [Release/obj.target/edge_coreclr/src/common/edge.o] Error 1
make: Leaving directory '/tmp/simple-samples/edge-js/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Linux 4.9.125-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "build" "--target=v12.0.0"
gyp ERR! cwd /tmp/simple-samples/edge-js
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok
```

I could address this issue by modifying the `src/common/edge.cpp` file.

```cpp
v8::Isolate * isolate = v8::Isolate::GetCurrent();
v8::Local<v8::Context> context = isolate->GetCurrentContext();
```

But I now get a new one.

```
root@dc71ba70a640:/tmp/simple-samples/edge-js# node-gyp build --target=$(node --version)
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@12.0.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/tmp/simple-samples/edge-js/build'
  CXX(target) Release/obj.target/edge_coreclr/src/common/edge.o
../src/common/edge.cpp: In function 'void init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)':
../src/common/edge.cpp:69:80: error: no matching function for call to 'Set(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE&, v8::Local<v8::String>, v8::MaybeLocal<v8::Function>)'
         Nan::New<v8::FunctionTemplate>(initializeClrFunc)->GetFunction(context));
                                                                                ^
In file included from ../node_modules/nan/nan.h:217:0,
                 from ../src/common/edge_common.h:8,
                 from ../src/common/edge.cpp:5:
../node_modules/nan/nan_maybe_43_inl.h:87:20: note: candidate: Nan::Maybe<bool> Nan::Set(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>)
 inline Maybe<bool> Set(
                    ^~~
../node_modules/nan/nan_maybe_43_inl.h:87:20: note:   no known conversion for argument 3 from 'v8::MaybeLocal<v8::Function>' to 'v8::Local<v8::Value>'
../node_modules/nan/nan_maybe_43_inl.h:96:20: note: candidate: Nan::Maybe<bool> Nan::Set(v8::Local<v8::Object>, uint32_t, v8::Local<v8::Value>)
 inline Maybe<bool> Set(
                    ^~~
../node_modules/nan/nan_maybe_43_inl.h:96:20: note:   no known conversion for argument 2 from 'v8::Local<v8::String>' to 'uint32_t {aka unsigned int}'
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-unused-private-field'
cc1plus: warning: unrecognized command line option '-Wno-redundant-move'
cc1plus: warning: unrecognized command line option '-Wno-mismatched-tags'
edge_coreclr.target.mk:133: recipe for target 'Release/obj.target/edge_coreclr/src/common/edge.o' failed
make: *** [Release/obj.target/edge_coreclr/src/common/edge.o] Error 1
make: Leaving directory '/tmp/simple-samples/edge-js/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Linux 4.9.125-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "build" "--target=v12.0.0"
gyp ERR! cwd /tmp/simple-samples/edge-js
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok
```

Hope these infos can help.

**Comment by informaticienzero** [comment]
In fact, I managed to get a correction of all the code. Almost all corrections are missing `context` or conversions from `MaybeValue` to `Value`. But I don't know if my code is correct and if the code is really working. Haven't try it enough. 

I keep on my investigations.

**Comment by agracio** [comment]
Your conversions should be correct if you followed the same concept of `context` and `MaybeValue` as in existing code. I already converted some during Node.js 11.x update.

**Comment by agracio** [comment]
If you completed your changes I will be happy to merge and release. Don't want to go through all that pain again :)

**Comment by agracio** [comment]
Actually ignore that, already started conversion using Nan instead.

**Comment by agracio** [comment]
New version with Node.js 12.x support published to npm.

**Comment by informaticienzero** [comment]
Thanks a lot for your work. Sorry I couldn't have help more.

So, is the use of Nan a big deal? What did it change?

**Comment by agracio** [comment]
Converting to Nan functions instead of using new V8 functions allows the code to be compatible with both old and new versions of V8. So if you were to convert everything to new V8 functions older versions like Node.js 6 and 8 would no longer compile.

**Comment by porsager** [comment]
nwjs up until 0.38.4 (node 12.3.1) works well with edge-js 👍
