### ISSUE TITLE
System.ArgumentException: Illegal Characters in Path

### ISSUE THREAD

**Issue by huoxiangdong** [agracio/edge-js#87]
System.ArgumentException: Illegal Characters in Path。
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at System.ComponentModel.Design.RuntimeLicenseContext.GetSavedLicenseKey(Type type, Assembly resourceAssembly)
   at System.ComponentModel.LicenseManager.LicenseInteropHelper.GetCurrentContextInfo(Int32& fDesignTime, IntPtr& bstrKey, RuntimeTypeHandle rth)
   at Startup.<Invoke>d__0.MoveNext()
someInputString

`
var getCat = edge.func({
    source: path.join(__dirname, '\\test.cs')
    , references: [
        __dirname + '\\Interop.BarTender.dll' ]）

using System.Threading.Tasks;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using BarTender;

public class Startup
{

    public async Task<object> Invoke(object input)
    {
  
          try {
           // error
            BarTender.Application btApp = new BarTender.Application();
          } catch (Exception ex) {
             Console.WriteLine(ex);
          }
          
            return input.ToString();

        }
    }
`

**Comment by jkash20** [comment]
Hi @huoxiangdong, were you able to resolve this issue?
I'm facing the exact the same issue. The node version that I'm using is 12.16.2 32 bit. Any help on this would be highly appreciated as we have been trying to resolve this issue for the past 3 days.

**Comment by EGSatelix** [comment]
Hi,
Same problem when creating new objet from dll interop...

**Comment by DaSpawn** [comment]
Bartender needs/is trying to invoke methods on the calling/parent window to test permissions.  You need to pass a parentWindow to the start function and Bartender will open/function as expected

for example:

[DllImport("user32.dll", SetLastError = true)]
static extern IntPtr GetForegroundWindow();

IntPtr ParentHandle = GetForegroundWindow();

BarTender.Application btApp = new BarTender.Application();

btApp.Start(ParentHandle);

**Comment by huoxiangdong** [comment]
@DaSpawn tks!!!
